[package]
name = "allegro_window"
version = "0.1.0"
authors = ["Damien Radtke <damienradtke@gmail.com>"]

[dependencies]
allegro = "0.0.30"
pistoncore-event_loop = "0.33.0"
pistoncore-input = "0.19.0"
pistoncore-window = "0.28.0"
